---
- name: Ensure dependencies are installed
  package:
    name:
      - git
      - socat
      - curl
    state: present

- name: Install acme.sh if not already installed
  git:
    repo: "https://github.com/acmesh-official/acme.sh.git"
    dest: "{{ acme_install_dir }}"
    version: master
  register: acme_git

- name: Run acme.sh install script
  command: "./acme.sh --install --accountemail {{ email }}"
  args:
    chdir: "{{ acme_install_dir }}"
  when: acme_git.changed

- name: Ensure HAProxy TLS directory exists
  file:
    path: "{{ haproxy_tls_dir }}"
    state: directory
    mode: "0750"
    owner: root
    group: haproxy

- name: "Request cert for {{cert.name}}"
  include_tasks: cert.yaml
  loop: "{{ certs }}"
  loop_control:
    loop_var: cert
