is_lighthouse: true
nebula_ip: 100.64.0.3

nebula_name: "lighthouse-03.lab"

ipv6: "2a03:94e0:ffff:185:125:168::191"
ipv4: "185.125.168.191"

ansible_host: "{{ ipv6 }}"
ansible_user: "root"

ansible_python_interpreter: /usr/bin/python3.11