---
- name: install unbound
  apt:
    name: unbound
    state: present

- name: Set unbound config
  template:
    src: templates/server.conf.j2
    dest: /etc/unbound/unbound.conf.d/server.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - "reload unbound.service"